import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import TabsComponent from "../Components/About/TabsComponent";
import { CssBaseline, Divider } from "@mui/material";
import About from "../Components/About/About";
import Footer from "../Components/Footer/Footer";

import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useEffect, useRef } from "react";

gsap.registerPlugin(ScrollTrigger);
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nate|Frontend dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main style={{ overflow: "hidden" }}>
        <CssBaseline />
        <About />
      </main>
      <footer
      // style={{ background: "#222d3d", height: "", color: "whitesmoke" }}
      >
        <Footer />
      </footer>
    </>
  );
}
